plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'be'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-batch:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter-security:3.4.5'
    implementation 'org.springframework.security:spring-security-oauth2-jose'
    implementation 'org.springframework.security:spring-security-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-validation:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.5'
    implementation 'org.springframework.boot:spring-boot-starter-mail:3.4.5'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.3.3'
    implementation 'mysql:mysql-connector-java:8.0.33'

    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // for JSON serialization

    // Development Tools
    developmentOnly 'org.springframework.boot:spring-boot-devtools:3.4.5'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.4.5'
    testImplementation 'org.springframework.batch:spring-batch-test:5.2.2'

    // Configuration Processor
    implementation 'org.springframework.boot:spring-boot-configuration-processor:3.4.5'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    // PostgreSQL Driver
    runtimeOnly 'org.postgresql:postgresql:42.7.5'

    // Apache Commons Lang
    implementation 'org.apache.commons:commons-lang3:3.12.0'

    // Apache Commons Collections
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

tasks.named('test') {
    useJUnitPlatform()
}
